name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.34.1
      - run: docker-compose pull
      - uses: jpribyl/action-docker-layer-caching@v0.1.1
        continue-on-error: true
      - run: |
          cp .env.sample .env
          docker-compose up -d
          make migrate-db
          make test
